package sbnz.cep;

import sbnz.integracija.example.model.Reservation;
import sbnz.integracija.example.model.User;
import sbnz.integracija.example.event.ReservationEvent;

rule "More than 5 reservations in 10 minutes from one client"
    when
    	$u: User(status == User.Status.ACTIVE)
        $r1: ReservationEvent($cId: reservation.user.getId())
        Number(intValue >=5) from accumulate(
            $r2: ReservationEvent(
                this != $r1, 
                reservation.user.getId() == $cId, 
                this meets[10m] $r1
            ),
            count($r2)
        )
    then
    	modify($u) {setStatus(User.Status.BLOCKED)}
        System.out.println("aaaa doso sam ovde jer je kriticno: Status rezervacije: " + $r1.getReservation().getStatus());
end
