package sbnz.cep;
import sbnz.integracija.example.model.User;
import sbnz.integracija.example.model.Reservation;

rule "New reservation - promote to PLATINUM"
salience 50/User.Category.PLATINUM.getValue()
when
		$r1: Reservation(status == Reservation.Status.RESERVED)
		$u: User(category.getValue() == User.Category.PLATINUM.getValue()-1)
		Number(intValue >= 4) from accumulate(
			$r2: Reservation(
				this != $r1,
				status.getValue() == 2,
				user.getId() == $u.getId()
			),
			count($r2)
		)
	then
		modify($u) {setCategory(User.Category.PLATINUM);}
end

rule "New reservation - promote to GOLD"
salience 50/User.Category.GOLD.getValue()
when
		$r1: Reservation(status == Reservation.Status.RESERVED)
		$u: User(category.getValue() == User.Category.GOLD.getValue()-1)
		Number(intValue >= 3) from accumulate(
			$r2: Reservation(
				this != $r1,
				status.getValue() == 2,
				user.getId() == $u.getId()
			),
			count($r2)
		)
	then
		modify($u) {setCategory(User.Category.GOLD);}
end

rule "New reservation - promote to SILVER"
salience 50/User.Category.SILVER.getValue()
when
		$r1: Reservation(status == Reservation.Status.RESERVED)
		$u: User(category.getValue() == User.Category.SILVER.getValue()-1)
		Number(intValue >= 2) from accumulate(
			$r2: Reservation(
				this != $r1,
				status.getValue() == 2,
				user.getId() == $u.getId()
			),
			count($r2)
		)
	then
		modify($u) {setCategory(User.Category.SILVER);}
end


