package sbnz.cep;

import sbnz.integracija.example.model.Reservation;
import sbnz.integracija.example.model.User;

rule "New reservation - promote to Silver"
	salience 10
	when
		$r1: Reservation(status == Reservation.Status.RESERVED)
		$u: User(category == User.Category.BRONZE)
		Number(intValue >= 3) from accumulate(
			$r2: Reservation(
				this != $r1,
				user.getId() == $u.getId()
			),
			count($r2)
		)
	then
		System.out.println("silver");
		modify($u) {setCategory(User.Category.SILVER);}
end

rule "New reservation - promote to Gold"
	salience 5
	when
		$r1: Reservation(status == Reservation.Status.RESERVED)
		$u: User(category == User.Category.SILVER)
		Number(intValue >= 6) from accumulate(
			$r2: Reservation(
				this != $r1,
				user.getId() == $u.getId()
			),
			count($r2)
		)
	then
		System.out.println("gold");
		modify($u) {setCategory(User.Category.GOLD);}

end		
rule "New reservation - promote to Platinum"
	salience 2
	when
		$r1: Reservation(status == Reservation.Status.RESERVED)
		$u: User(category == User.Category.GOLD)
		Number(intValue >= 10) from accumulate(
			$r2: Reservation(
				this != $r1,
				user.getId() == $u.getId()
			),
			count($r2)
		)
	then
		System.out.println("platinum");
		modify($u) {setCategory(User.Category.PLATINUM);}	
end	