package sbnz.reservation;


import sbnz.integracija.example.model.Reservation;
import sbnz.integracija.example.model.User;
import sbnz.integracija.example.model.Accommodation;
import java.util.*;

global Integer visits;

rule "calculate price based on duration of reservation"
	salience 110
	agenda-group "reservation-price"
	when
        $r: Reservation(status == Reservation.Status.PENDING,start : startDate.getDayOfYear(), endd : endDate.getDayOfYear())
        $a: Accommodation(price : pricePerDay)
    then
        System.out.println("dosao");
        modify($r){setTotalPrice((endd-start)*price);}
        modify($r){setStatus(Reservation.Status.CONFIRMED);}
end

rule "calculate discount based on number of stays at this particular owner if stays are more than 3 and less than 7 and apply 5% discount"
	salience 100
	agenda-group "reservation-price"
	when
		$r: Reservation($totalPrice : totalPrice,status == Reservation.Status.CONFIRMED, $user : user) @Watch(!*,status)
		$a: Accommodation($owner : owner)
		$rezervacije : Set() from collect(Reservation(status == Reservation.Status.RESERVED) from $user.getReservations())
		$numOfUniqueVisits: Set() from accumulate (
			Reservation (
				$id : id
			) from $rezervacije,
			collectSet($id)
			
		)
		
		eval($numOfUniqueVisits.size() >= 3)
		eval($numOfUniqueVisits.size() < 7)
	then
		System.out.println("3 do 7");
		modify($r){setTotalPrice($totalPrice*0.95)}
end

rule "calculate discount based on number of stays at this particular owner if stays are more than 7 and less than 10 and apply 10% discount"
	agenda-group "reservation-price"
	salience 100/visits
	when
		$r: Reservation($totalPrice : totalPrice,status == Reservation.Status.CONFIRMED,$user : user) @Watch(!*,status)
		$a: Accommodation($owner : owner)
		$rezervacije : Set() from collect(Reservation(status == Reservation.Status.RESERVED) from $user.getReservations())
		$numOfUniqueVisits: Set() from accumulate (
			Reservation (
				$id : id
			) from $rezervacije,
			collectSet($id)
			
		)
		
		eval($numOfUniqueVisits.size() >= 7)
		eval($numOfUniqueVisits.size() < 10)
		
	
	then
		System.out.println("7 do 10");
		modify($r){setTotalPrice($totalPrice*0.90)}
end

rule "calculate discount based on number of stays at this particular owner if stays are more than 10 apply 15% discount"
	salience 100/visits
	agenda-group "reservation-price"
	when
		$r: Reservation($totalPrice : totalPrice,status == Reservation.Status.CONFIRMED, $user : user) @Watch(!*,status)
		$a: Accommodation($owner : owner)
		$rezervacije : Set() from collect(Reservation(status == Reservation.Status.RESERVED) from $user.getReservations())
		$numOfUniqueVisits: Set() from accumulate (
			Reservation (
				$id : id
			) from $rezervacije,
			collectSet($id)
			
		)
		eval($numOfUniqueVisits.size() >= 10)
		
		
	
	then
		System.out.println("preko 10"); 
		modify($r){setTotalPrice($totalPrice*0.85)}
end
