package sbnz.accommodation;

import sbnz.integracija.example.model.Accommodation;
import sbnz.integracija.example.model.User;

rule "Apply discount 3%"
	agenda-group "accommodation-discount"
	lock-on-active true
    when
    	$u: User(category == User.Category.SILVER)
        $a: Accommodation()
    then
        modify($a){setDiscount((double)3)}
end


rule "Apply discount 5%"
	agenda-group "accommodation-discount"
	lock-on-active true
    when
    	$u: User(category == User.Category.GOLD)
        $a: Accommodation()
    then
        modify($a){setDiscount((double)5)}
end


rule "Apply discount 10%"
	agenda-group "accommodation-discount"
	lock-on-active true
    when
    	$u: User(category == User.Category.PLATINUM)
        $a: Accommodation()
    then
        modify($a){setDiscount((double)10)}
end