package sbnz.accommodation;

import sbnz.integracija.example.model.Accommodation;
import sbnz.integracija.example.model.User;

rule "Apply discount 3%"
	agenda-group "accommodation-discount"
	lock-on-active true
    when
    	$u: User(category == User.Category.SILVER)
        $a: Accommodation(price : pricePerDay)
    then
        modify($a){setPricePerDay(price*0.97);}
end


rule "Apply discount 5%"
	agenda-group "accommodation-discount"
	lock-on-active true
    when
    	$u: User(category == User.Category.GOLD)
        $a: Accommodation(price : pricePerDay)
    then
        modify($a){setPricePerDay(price*0.95);}
end


rule "Apply discount 10%"
	agenda-group "accommodation-discount"
	lock-on-active true
    when
    	$u: User(category == User.Category.PLATINUM)
        $a: Accommodation(price : pricePerDay)
    then
        modify($a){setPricePerDay(price*0.90);}
end