package sbnz.user;
import sbnz.integracija.example.model.User;
import sbnz.integracija.example.model.Reservation;

rule "Categorize Users_PLATINUM"
salience 50/User.Category.PLATINUM.getValue()
agenda-group "user-category"
when
	$u: User(category.getValue() == User.Category.PLATINUM.getValue()-1)
        Number(intValue >= 4) from accumulate(
			$r2: Reservation(
				user.getId() == $u.getId(),
				status.getValue() == 2
			),
			count($r2)
		)
then
	modify ($u){ setCategory(User.Category.PLATINUM)};
end

rule "Categorize Users_GOLD"
salience 50/User.Category.GOLD.getValue()
agenda-group "user-category"
when
	$u: User(category.getValue() == User.Category.GOLD.getValue()-1)
        Number(intValue >= 3) from accumulate(
			$r2: Reservation(
				user.getId() == $u.getId(),
				status.getValue() == 2
			),
			count($r2)
		)
then
	modify ($u){ setCategory(User.Category.GOLD)};
end

rule "Categorize Users_SILVER"
salience 50/User.Category.SILVER.getValue()
agenda-group "user-category"
when
	$u: User(category.getValue() == User.Category.SILVER.getValue()-1)
        Number(intValue >= 2) from accumulate(
			$r2: Reservation(
				user.getId() == $u.getId(),
				status.getValue() == 2
			),
			count($r2)
		)
then
	modify ($u){ setCategory(User.Category.SILVER)};
end


